### ISSUE TITLE
wrapper_download.sh

### ISSUE THREAD

**Issue by jasonebox** [BaptisteVandecrux/SICE#7]
can wrapper_download.sh have a destination dir please

**Comment by BaptisteVandecrux** [comment]
wrapper_download.sh --date YYYY-MM -o out_path ...
will now download files in out_path/YYYY-MM/DD/*.sen3

note also that there is a new option 
wrapper_download.sh --date YYYY-MM -o out_path -s S3A/S3B/all
to select satellite
